### ISSUE TITLE
Maximum amount of 100 items show in gallery

### ISSUE THREAD

**Issue by WKnol** [Esri/map-and-app-gallery#7]
Currently we have a great number of items shared using this gallery.
But if i put the filters on all categories and on all types not everything is show.

It looks like there is a maximum of 100 items show using the gallery.
Is this a known issue?

**Comment by allisonmuise** [comment]
@WKnol 
This is a known issue for this application. This application is no longer being actively developed so there is no intention to fix this at this time. 

We have developed an ArcGIS Online gallery application template to replace this on-premises app, but it too has issues with 100 items or more. We are working to fix this issues in a future release of this online app.

http://www.arcgis.com/home/item.html?id=8fe02db25bf246dea36b45c5a95728b3
